//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otomata.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CarServiceSoap")]
    public interface CarServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Oku", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Oku();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Oku", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> OkuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kirala", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Kirala();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kirala", ReplyAction="*")]
        System.Threading.Tasks.Task<string> KiralaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CarServiceSoapChannel : Otomata.ServiceReference1.CarServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarServiceSoapClient : System.ServiceModel.ClientBase<Otomata.ServiceReference1.CarServiceSoap>, Otomata.ServiceReference1.CarServiceSoap {
        
        public CarServiceSoapClient() {
        }
        
        public CarServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Oku() {
            return base.Channel.Oku();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> OkuAsync() {
            return base.Channel.OkuAsync();
        }
        
        public string Kirala() {
            return base.Channel.Kirala();
        }
        
        public System.Threading.Tasks.Task<string> KiralaAsync() {
            return base.Channel.KiralaAsync();
        }
    }
}
